spring:
    application:
        name: back_end
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081
server:
    port: 8080

# spring.security.user.name=admin
# spring.security.user.password=admin